- name: install core dev packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - build-essential
    - git
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes

- name: user desired packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=86400
  with_items: user_packages
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes

- name: Make repos dir
  file: path="{{ home_directory }}/{{ personal_repos_path }}" state=directory
  when: personal_repos_path is defined
  become: no

- name: Ensure personal bin dir exists
  file: path="{{ home_directory }}/bin" state=directory
  become: no

- include: use-setup-git-repo.yaml
  when: use_setup_git_repo

- name: Personal git repos
  git:
    repo="{{ item.repo }}"
    dest="{{ home_directory }}/{{ personal_repos_path }}/{{ item.name }}"
    update=no
  with_items: personal_repos
  become: no

- name: setup dot files
  command: "{{ dotfiles.command }}"
  args:
    chdir: "{{ dotfiles.path }}"
    creates: "{{ dotfiles.creates }}"
  when: dotfiles is defined
  become: no
