- name: python packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=86400
  with_items: python_packages
  sudo: yes

- name: Python tools and bits
  pip:
    name={{ item }}
  with_items:
    - virtualenv
    - tox
  sudo: yes
